# H1 TITLE
## H2 TITLE


In [1]:
print("Buy the dip ?")

Buy the dip ?


In [2]:
import numpy as np


In [3]:
# Exercise 1: Your first NumPy array

ex1Array = np.array([1, 3.14, 'Hello', {'key': 'value'}, [1, 2, 3], (4, 5, 6), {7, 8, 9}, True], dtype=object)
for i in ex1Array:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [17]:
# Exercise 2: Zeros
zeros_array = np.zeros(300)
print("2.1")
print(zeros_array, '\n')
print("2.2")
reshaped_array = zeros_array.reshape(3, 100)
print(reshaped_array)



2.1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

2.2
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  

In [16]:
# Exercise 3: Slicing
slice_array = np.arange(1,101)
print("3.1")
print(slice_array, '\n')
odd_array = slice_array[slice_array % 2 == 1]
print("3.2")
print(odd_array, '\n')
reverse_even_array = slice_array[slice_array % 2 == 0][::-1]
print("3.3")
print(reverse_even_array, '\n')
every_third_is_zero_array = slice_array
every_third_is_zero_array[1::3] = 0
print("3.4")
print(every_third_is_zero_array, '\n')

3.1
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

3.2
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99] 

3.3
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2] 

3.4
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   

In [18]:
# Exercise 4: Random
# setting rng seed
np.random.seed(888)
print("4.1")
print("np.random.seed(888)", "\n")

rngArr1 = np.random.randn(100)
print("4.2")
print(rngArr1, "\n")

rngArr2 = np.random.randint(1,11,(8,8))
print("4.3")
print(rngArr2, "\n")

rngArr3 = np.random.randint(1,18,(4,2,5))
print("4.4")
print(rngArr3, "\n")

4.1
np.random.seed(888) 

4.2
[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762

In [23]:
# Exercise 5: Split, concatenate, reshape arrays

ex5ArrayLow = np.arange(1, 51)
print(ex5ArrayLow, "\n")
ex5ArrayHigh = np.arange(51, 101)
print(ex5ArrayHigh, "\n")
exConcatenate = np.concatenate((ex5ArrayLow, ex5ArrayHigh))
print(exConcatenate, "\n")
exReshape = np.reshape(exConcatenate, (10,10))
print(exReshape, "\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100] 

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53 

In [24]:
# Exercise 6: Broadcasting and Slicing

# 6.1
ex6Array2d = np.ones((9, 9), dtype=np.int8)
print(ex6Array2d, "\n")
# 6.2
ex6Array2d[1:-1, 1:-1] = 0
ex6Array2d[2, 2:7] = 1
ex6Array2d[3:6, 4] = 1
ex6Array2d[4, 2:8:2] = 1
ex6Array2d[6, 2:7] = 1
print(ex6Array2d, "\n")
# 6.3
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
np.reshape(array_1, (5, 1)) * array_2
print(np.reshape(array_1, (5, 1)) * array_2)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]] 



In [9]:
# Exercise 7: NaN


generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
# print(grades)

gradesWhere = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])
# print(gradesWhere)
gradesInsert = np.insert(arr = grades, values = gradesWhere, axis = 1, obj = 2)
print(gradesInsert)




[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [10]:
# Exercise 8: Wine

# Load the data using genfromtxt and optimize types
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = np.genfromtxt(url, delimiter=';', skip_header=1, dtype=np.float32)

# Check memory usage
print(f"Memory Usage: {data.nbytes} bytes")

# Print 2nd, 7th, and 12th rows
selected_rows = data[[1, 6, 11], :]
print("Selected Rows:")
print(selected_rows)

# Check if any wine has alcohol percentage greater than 20%
has_high_alcohol = np.any(data[:, 10] > 20)
print(f"Any wine with alcohol > 20%: {has_high_alcohol}")

# Compute average % of alcohol, dropping NaN values
average_alcohol = np.nanmean(data[:, 10])
print(f"Average % of alcohol: {average_alcohol}")

# Compute statistics for pH
ph_stats = {
    'Minimum': np.min(data[:, 8]),
    'Maximum': np.max(data[:, 8]),
    '25th Percentile': np.percentile(data[:, 8], 25),
    '50th Percentile (Median)': np.median(data[:, 8]),
    '75th Percentile': np.percentile(data[:, 8], 75),
    'Mean': np.mean(data[:, 8])
}
print("pH Statistics:")
for key, value in ph_stats.items():
    print(f"{key}: {value}")

# Compute average quality of wines with the 20% least sulphates
percentile_20 = np.percentile(data[:, 5], 20)
average_quality_20 = np.mean(data[data[:, 5] < percentile_20, 11])
print(f"Average quality of wines with 20% least sulphates: {average_quality_20}")

# Identify best and worst quality wines
best_quality = np.argmax(data[:, 11])
worst_quality = np.argmin(data[:, 11])

# Compute mean of all variables for wines with the best quality
mean_best_quality = np.mean(data[best_quality, :])

# Compute mean of all variables for wines with the worst quality
mean_worst_quality = np.mean(data[worst_quality, :])

print("Mean of all variables for the best quality wine:")
print(mean_best_quality)

print("Mean of all variables for the worst quality wine:")
print(mean_worst_quality)

Memory Usage: 76752 bytes
Selected Rows:
[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]
Any wine with alcohol > 20%: False
Average % of alcohol: 10.42298412322998
pH Statistics:
Minimum: 2.740000009536743
Maximum: 4.010000228881836
25th Percentile: 3.2100000381469727
50th Percentile (Median): 3.309999942779541
75th Percentile: 3.4000000953674316
Mean: 3.3111133575439453
Average quality of wines with 20% least sulphates: 5.5929646492004395
Mean of all variables for the best quality wine:
7.532942
Mean of all variables for the worst quality wine:
7.411234


In [11]:
# Exercise 8: Wine; practice data

# Load the data using genfromtxt and optimize types
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = np.genfromtxt(url, delimiter=';', dtype=np.float32)
print("All data:")
print(data)

# Check that the numpy array weights **76800 bytes**.
array_size_bytes = data.nbytes
print("Data weight:", array_size_bytes, "bytes")
# Print 2nd, 7th and 12th rows as a two dimensional array
selected_rows = data[[1, 4, 7], :]
print("Lines 2, 7 and 12:")
print(selected_rows)
# Is there any wine with a percentage of alcohol greater than 20% ?
has_high_alcohol = np.any(data[:, 10] > 20)
print("Any wine with alcohol > 20%: ", has_high_alcohol)
# Compute the minimum, the maximum, the 25th percentile, the 50th percentile, the 75th percentile, the mean of the pH
# data line 0 is the headers, so is not a number; excluding it lets us find the min in the rest of the data
minimum =  np.min(data[1:, 8])
print("minimum: ", minimum)
maximum =  np.max(data[1:, 8])
print("maximum: ", maximum)
Perc25 = np.percentile(data[1:, 8], 25)
print("25th Percentile: ", round(Perc25, 3))
Perc50 = np.percentile(data[1:, 8], 50)
print("50th Percentile: ", round(Perc50, 3))
Perc75 = np.percentile(data[1:, 8], 75)
print("75th Percentile: ", round(Perc75, 3))
# Compute the average quality of the wines having the 20% least sulphates
data_without_header = data[1:, :]
sulphates_data = data_without_header[:, 5]
selected_rows = data_without_header[sulphates_data >= 20, :]
quality_values = selected_rows[:, -2]
average_quality = np.mean(quality_values)

print("Average quality of wines with at least 20pc sulphates:", average_quality)
# This is wildly wrong, need to redo


All data:
[[   nan    nan    nan ...    nan    nan    nan]
 [ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
Data weight: 76800 bytes
Lines 2, 7 and 12:
[[ 7.4     0.7     0.      1.9     0.076  11.     34.      0.9978  3.51
   0.56    9.4     5.    ]
 [11.2     0.28    0.56    1.9     0.075  17.     60.      0.998   3.16
   0.58    9.8     6.    ]
 [ 7.9     0.6     0.06    1.6     0.069  15.     59.      0.9964  3.3
   0.46    9.4     5.    ]]
Any wine with alcohol > 20%:  False
minimum:  2.74
maximum:  4.01
25th Percentile:  3.21
50th Percentile:  3.31
75th Percentile:  3.4
Average quality of wines with at least 20pc sulphates: 10.332977


In [12]:
from itertools import permutations

# Load the model forecasts from the file
model_forecasts = np.genfromtxt('model_forecasts.txt', delimiter=',', filling_values=np.nan)

# Get the number of teams
num_teams = len(model_forecasts)

# Generate all possible permutations of teams
team_permutations = list(permutations(range(num_teams), 2))

# Initialize variables to keep track of the minimum sum of squared differences and corresponding pair
min_sum_squares = float('inf')
min_pair = None

# Iterate through all team permutations
for pair in team_permutations:
    team1, team2 = pair
    # Calculate the sum of squared differences for the current pair
    sum_squares = np.sum((model_forecasts[:, team1] - model_forecasts[:, team2])**2)
    
    # Update minimum sum and corresponding pair if the current pair has a lower sum
    if sum_squares < min_sum_squares:
        min_sum_squares = sum_squares
        min_pair = pair

print("Pairs that will give the most interesting matches:")
print(min_pair)


Pairs that will give the most interesting matches:
None
