# H1 TITLE
## H2 TITLE


In [69]:
print("Buy the dip ?")

Buy the dip ?


In [70]:
import numpy as np


In [71]:
# Exercise 1: Your first NumPy array

ex1Array = np.array([1, 3.14, 'Hello', {'key': 'value'}, [1, 2, 3], (4, 5, 6), {7, 8, 9}, True], dtype=object)
for i in ex1Array:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [72]:
# Exercise 2: Zeros
zeros_array = np.zeros(300)
print("2.1")
print(zeros_array, '\n')
print("2.2")
reshaped_array = zeros_array.reshape(3, 100)
print(reshaped_array)



2.1
[0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00
 0

In [73]:
# Exercise 3: Slicing
slice_array = np.arange(1,101)
print("3.1")
print(slice_array, '\n')
odd_array = slice_array[slice_array % 2 == 1]
print("3.2")
print(odd_array, '\n')
reverse_even_array = slice_array[slice_array % 2 == 0][::-1]
print("3.3")
print(reverse_even_array, '\n')
every_third_is_zero_array = slice_array
every_third_is_zero_array[1::3] = 0
print("3.4")
print(every_third_is_zero_array, '\n')

3.1
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

3.2
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99] 

3.3
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2] 

3.4
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   

In [74]:
# Exercise 4: Random
# setting rng seed
np.random.seed(888)
print("4.1")
print("np.random.seed(888)", "\n")

rngArr1 = np.random.randn(100)
print("4.2")
print(rngArr1, "\n")

rngArr2 = np.random.randint(1,11,(8,8))
print("4.3")
print(rngArr2, "\n")

rngArr3 = np.random.randint(1,18,(4,2,5))
print("4.4")
print(rngArr3, "\n")

4.1
np.random.seed(888) 

4.2
[-0.18  0.19  0.83 -0.03 -0.65 -0.11  0.22  0.59  0.10 -1.10 -0.26  0.41
  0.16  1.04  0.22  0.70 -0.87 -1.39 -0.24 -0.76  1.31 -0.98 -0.36  0.12
 -0.35 -0.44 -0.05 -0.43 -1.09 -2.31 -1.86  0.23 -0.90 -0.54 -0.40  0.02
  0.18 -0.57 -0.34 -0.00  1.45  1.37  2.69  0.68 -1.06  0.13  0.17  0.09
  1.04 -0.14 -0.37  3.20  1.11 -0.26  1.48 -1.57  0.98  1.76  0.35 -0.31
 -1.40 -0.65 -1.38 -0.24 -1.18  0.70  0.28 -1.02  1.10  0.24 -0.37 -2.20
  1.42  0.22  0.79 -0.22 -0.70 -0.92 -1.47  1.88  1.51  0.12  0.65 -0.71
  1.70  1.35  0.53 -0.61 -0.18 -1.29  1.42 -0.18 -0.10 -0.60  1.20  0.96
  0.86  1.96 -1.16  0.35] 

4.3
[[ 9  8  4  6  9  1  3  2]
 [ 3  9  9  5  4  7  2  8]
 [ 5  6  9  1  1  6  8  7]
 [ 7  1  4  1 10  4  3  5]
 [ 5 10  1 10  7 10  6  1]
 [ 6  8  7  4  6 10  3  5]
 [ 4 10  7  9  9 10  9  9]
 [ 5  3  2 10  8  5  5  3]] 

4.4
[[[ 5  2 13 16 15]
  [ 5  5  2 11  3]]

 [[ 8 13  6  4 17]
  [ 2  8  1 13 10]]

 [[12 17 17 12  1]
  [10  8 17  5 11]]

 [[ 9 14  2

In [75]:
# Exercise 5: Split, concatenate, reshape arrays

ex5ArrayLow = np.arange(1, 51)
print(ex5ArrayLow, "\n")
ex5ArrayHigh = np.arange(51, 101)
print(ex5ArrayHigh, "\n")
exConcatenate = np.concatenate((ex5ArrayLow, ex5ArrayHigh))
print(exConcatenate, "\n")
exReshape = np.reshape(exConcatenate, (10,10))
print(exReshape, "\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100] 

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53 

In [76]:
# Exercise 6: Broadcasting and Slicing

# 6.1
ex6Array2d = np.ones((9, 9), dtype=np.int8)
print(ex6Array2d, "\n")
# 6.2
ex6Array2d[1:-1, 1:-1] = 0
ex6Array2d[2, 2:7] = 1
ex6Array2d[3:6, 4] = 1
ex6Array2d[4, 2:8:2] = 1
ex6Array2d[6, 2:7] = 1
print(ex6Array2d, "\n")
# 6.3
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
np.reshape(array_1, (5, 1)) * array_2
print(np.reshape(array_1, (5, 1)) * array_2)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [77]:
# Exercise 7: NaN


generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
# print(grades)

gradesWhere = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])
# print(gradesWhere)
gradesInsert = np.insert(arr = grades, values = gradesWhere, axis = 1, obj = 2)
print(gradesInsert)




[[7.00 1.00 7.00]
 [ nan 2.00 2.00]
 [ nan 8.00 8.00]
 [9.00 3.00 9.00]
 [8.00 9.00 8.00]
 [ nan 2.00 2.00]
 [8.00 2.00 8.00]
 [ nan 6.00 6.00]
 [9.00 2.00 9.00]
 [8.00 5.00 8.00]]


In [94]:
# Exercise 8: Wine

# Load the data using genfromtxt and optimize types
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
optimised_data = np.genfromtxt(url, delimiter=';', skip_header=1, dtype=np.float32)

# Check memory usage
print("8.1")
print(f"Memory Usage: {optimised_data.nbytes} bytes")
# Verify if the dataset size criterion is met
if optimised_data.nbytes <= 76800:
    print("Data optimized successfully.", "\n")
else:
    print("Optimization criteria not met.", "\n")


# Print 2nd, 7th, and 12th rows
print("8.2")
selected_rows = optimised_data[[1, 6, 11]]
print("Selected Rows:")
print(selected_rows)

# Check if any wine has alcohol percentage greater than 20%
print("8.3")
has_high_alcohol = np.any(optimised_data[:, 10] > 20)
print(f"Any wine with alcohol > 20%: {has_high_alcohol}", "\n")

# Compute average % of alcohol, dropping NaN values
print("8.4")
average_alcohol = np.nanmean(optimised_data[:, 10])
print(f"Average % of alcohol: {average_alcohol}", "\n")

# Compute statistics for pH
print("8.5")
ph_stats = {
    '25th Percentile': np.percentile(optimised_data[:, 8], 25),
    '50th Percentile (Median)': np.median(optimised_data[:, 8]),
    '75th Percentile': np.percentile(optimised_data[:, 8], 75),
    'Mean': np.mean(optimised_data[:, 8]),
    'Minimum': np.min(optimised_data[:, 8]),
    'Maximum': np.max(optimised_data[:, 8])
}
for key, value in ph_stats.items():
    print(f"{key}: {value:.2f}")
print("\n")

# Compute average quality of wines with the 20% least sulphates
print("8.6")
percentile_20 = np.percentile(optimised_data[:, 9], 20)
average_quality_20 = optimised_data[optimised_data[:, 9] < percentile_20, 11].mean()
print(f"Average quality of wines with 20% least sulphates: {average_quality_20}", "\n")

# Identify best and worst quality wines
print("8.7")
best_quality = np.argmax(optimised_data[:, 11])
worst_quality = np.argmin(optimised_data[:, 11])


best_quality_indices = np.where(optimised_data[:, 11] == np.max(optimised_data[:, 11]))[0]
worst_quality_indices = np.where(optimised_data[:, 11] == np.min(optimised_data[:, 11]))[0]

# # Compute mean of all variables for wines with the best quality
mean_best_quality = np.mean(optimised_data[best_quality, :])

# # Compute mean of all variables for wines with the worst quality
mean_worst_quality = np.mean(optimised_data[worst_quality, :])

print("best quality wines:")
print(optimised_data[:, 11])

print("worst quality wine:")
print(worst_quality_indices)

print("\n")

8.1
Memory Usage: 76752 bytes
Data optimized successfully. 

8.2
Selected Rows:
[[  7.80   0.88   0.00   2.60   0.10  25.00  67.00   1.00   3.20   0.68
    9.80   5.00]
 [  7.90   0.60   0.06   1.60   0.07  15.00  59.00   1.00   3.30   0.46
    9.40   5.00]
 [  7.50   0.50   0.36   6.10   0.07  17.00 102.00   1.00   3.35   0.80
   10.50   5.00]]
8.3
Any wine with alcohol > 20%: False 

8.4
Average % of alcohol: 10.42298412322998 

8.5
25th Percentile: 3.21
50th Percentile (Median): 3.31
75th Percentile: 3.40
Mean: 3.31
Minimum: 2.74
Maximum: 4.01


8.6
Average quality of wines with 20% least sulphates: 5.185430526733398 

8.7
best quality wines:
[ 267  278  390  440  455  481  495  498  588  828 1061 1090 1120 1202
 1269 1403 1449 1549]
worst quality wine:
[ 459  517  690  832  899 1299 1374 1469 1478 1505]




In [79]:
# Exercise 8: Wine; practice data

# Load the data using genfromtxt and optimize types
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = np.genfromtxt(url, delimiter=';', dtype=np.float32)
print("All data:")
print(data)

# Check that the numpy array weights **76800 bytes**.
array_size_bytes = data.nbytes
print("Data weight:", array_size_bytes, "bytes")
# Print 2nd, 7th and 12th rows as a two dimensional array
selected_rows = data[[1, 4, 7], :]
print("Lines 2, 7 and 12:")
print(selected_rows)
# Is there any wine with a percentage of alcohol greater than 20% ?
has_high_alcohol = np.any(data[:, 10] > 20)
print("Any wine with alcohol > 20%: ", has_high_alcohol)
# Compute the minimum, the maximum, the 25th percentile, the 50th percentile, the 75th percentile, the mean of the pH
# data line 0 is the headers, so is not a number; excluding it lets us find the min in the rest of the data
minimum =  np.min(data[1:, 8])
print("minimum: ", minimum)
maximum =  np.max(data[1:, 8])
print("maximum: ", maximum)
Perc25 = np.percentile(data[1:, 8], 25)
print("25th Percentile: ", round(Perc25, 3))
Perc50 = np.percentile(data[1:, 8], 50)
print("50th Percentile: ", round(Perc50, 3))
Perc75 = np.percentile(data[1:, 8], 75)
print("75th Percentile: ", round(Perc75, 3))
# Compute the average quality of the wines having the 20% least sulphates
data_without_header = data[1:, :]
sulphates_data = data_without_header[:, 5]
selected_rows = data_without_header[sulphates_data >= 20, :]
quality_values = selected_rows[:, -2]
average_quality = np.mean(quality_values)

print("Average quality of wines with at least 20pc sulphates:", average_quality)
# This is wildly wrong, need to redo


All data:
[[  nan   nan   nan ...   nan   nan   nan]
 [ 7.40  0.70  0.00 ...  0.56  9.40  5.00]
 [ 7.80  0.88  0.00 ...  0.68  9.80  5.00]
 ...
 [ 6.30  0.51  0.13 ...  0.75 11.00  6.00]
 [ 5.90  0.64  0.12 ...  0.71 10.20  5.00]
 [ 6.00  0.31  0.47 ...  0.66 11.00  6.00]]
Data weight: 76800 bytes
Lines 2, 7 and 12:
[[ 7.40  0.70  0.00  1.90  0.08 11.00 34.00  1.00  3.51  0.56  9.40  5.00]
 [11.20  0.28  0.56  1.90  0.08 17.00 60.00  1.00  3.16  0.58  9.80  6.00]
 [ 7.90  0.60  0.06  1.60  0.07 15.00 59.00  1.00  3.30  0.46  9.40  5.00]]
Any wine with alcohol > 20%:  False
minimum:  2.74
maximum:  4.01
25th Percentile:  3.21
50th Percentile:  3.31
75th Percentile:  3.4
Average quality of wines with at least 20pc sulphates: 10.332977


In [80]:
from itertools import permutations

# Load the model forecasts from the file
model_forecasts = np.genfromtxt('model_forecasts.txt', delimiter=',', filling_values=np.nan)

# Get the number of teams
num_teams = len(model_forecasts)

# Generate all possible permutations of teams
team_permutations = list(permutations(range(num_teams), 2))

# Initialize variables to keep track of the minimum sum of squared differences and corresponding pair
min_sum_squares = float('inf')
min_pair = None

# Iterate through all team permutations
for pair in team_permutations:
    team1, team2 = pair
    # Calculate the sum of squared differences for the current pair
    sum_squares = np.sum((model_forecasts[:, team1] - model_forecasts[:, team2])**2)
    
    # Update minimum sum and corresponding pair if the current pair has a lower sum
    if sum_squares < min_sum_squares:
        min_sum_squares = sum_squares
        min_pair = pair

print("Pairs that will give the most interesting matches:")
print(min_pair)


Pairs that will give the most interesting matches:
None
