# H1 TITLE
## H2 TITLE


In [3]:
print("Buy the dip ?")

Buy the dip ?


In [4]:
import numpy as np


In [51]:
# Exercise 1

firstArray = np.array([1, 3.14, 'Hello', {'key': 'value'}, [1, 2, 3], (4, 5, 6), {7, 8, 9}, True], dtype=object)
for i in firstArray:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [ ]:
# Exercise 2
zeros_array = np.zeros(300)

reshaped_array = zeros_array.reshape(3, 100)

print(reshaped_array)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


In [53]:
# Exercise 3
slice_array = np.arange(1,101)
print(slice_array)
odd_array = slice_array[slice_array % 2 == 1]
print(odd_array)
reverse_even_array = slice_array[slice_array % 2 == 0][::-1]
print(reverse_even_array)
every_third_is_zero_array = slice_array
every_third_is_zero_array[1::3] = 0
print(every_third_is_zero_array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58

In [74]:
# Exercise 4
rng = np.random.seed(888)
# print(rng)
rngArr1 = np.random.randn(100)
# print(rngArr1)

np.random.seed(888)
rngArr2 = np.random.randint(1,11,(8,8))
print(rngArr2)

np.random.seed(888)
rngArr3 = np.random.randint(1,18,(4,2,5))
print(rngArr3)

[[ 7  4  8 10  2  1  1 10]
 [ 4  1  7  4  3  5  2  8]
 [ 3  9  7  4  9  6 10  5]
 [ 7 10  3 10  2  1  3  7]
 [ 3  2  3  2 10  9  5  4]
 [ 4  1  9  7  1  4  3  5]
 [ 3  2 10  8  6  3  9  4]
 [ 4  4  9  2  8  5  9  5]]
[[[14 16  8 15 14]
  [17 13  1  4 17]]

 [[ 7 15  2  8  3]
  [ 9  4 13  9 15]]

 [[ 5 11 11 14 10]
  [ 2  1 15  3  3]]

 [[ 3 10  5 16 13]
  [17 12  9  7 16]]]


In [80]:
# Exercise 5

ex5ArrayLow = np.arange(1, 51)
ex5ArrayHigh = np.arange(51, 101)
exConcatenate = np.concatenate((ex5ArrayLow, ex5ArrayHigh))
# print(exConcatenate)
exReshape = np.reshape(exConcatenate, (10,10))
# print(exReshape)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [85]:
# Exercise 6

# 6.1
ex6Array2d = np.ones((9, 9), dtype=np.int8)
# print(ex6Array2d)
# 6.2
ex6Array2d[1:-1, 1:-1] = 0
ex6Array2d[2, 2:7] = 1
ex6Array2d[3:6, 4] = 1
ex6Array2d[4, 2:8:2] = 1
ex6Array2d[6, 2:7] = 1
# print(ex6Array2d)
# 6.3
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
np.reshape(array_1, (5, 1)) * array_2
print(np.reshape(array_1, (5, 1)) * array_2)


[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [98]:
# Exercise 7
# Exercise 7
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
grades[[1, 2, 5, 7], [0, 0, 0, 0]] = np.nan

gradesWhere = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])

new_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Corrected usage of np.hstack to concatenate along the horizontal axis (axis=1)
gradesHStack = np.hstack((grades, new_vector[:, None]))

print(gradesHStack)





[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]
