# H1 TITLE
## H2 TITLE


In [299]:
print("Buy the dip ?")

Buy the dip ?


In [300]:
import numpy as np


In [301]:
# Exercise 1: Your first NumPy array

ex1Array = np.array([1, 3.14, 'Hello', {'key': 'value'}, [1, 2, 3], (4, 5, 6), {7, 8, 9}, True], dtype=object)
for i in ex1Array:
    print(type(i))


<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [302]:
# Exercise 2: Zeros
zeros_array = np.zeros(300)
print("2.1")
print(zeros_array, '\n')
print("2.2")
reshaped_array = zeros_array.reshape(3, 100)
print(reshaped_array)



2.1
[0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.

In [303]:
# Exercise 3: Slicing
slice_array = np.arange(1,101)
print("3.1")
print(slice_array, '\n')
odd_array = slice_array[slice_array % 2 == 1]
print("3.2")
print(odd_array, '\n')
reverse_even_array = slice_array[slice_array % 2 == 0][::-1]
print("3.3")
print(reverse_even_array, '\n')
every_third_is_zero_array = slice_array
every_third_is_zero_array[1::3] = 0
print("3.4")
print(every_third_is_zero_array, '\n')

3.1
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

3.2
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99] 

3.3
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2] 

3.4
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   

In [304]:
# Exercise 4: Random
# setting rng seed
np.random.seed(888)
print("4.1")
print("np.random.seed(888)", "\n")

rngArr1 = np.random.randn(100)
print("4.2")
print(rngArr1, "\n")

rngArr2 = np.random.randint(1,11,(8,8))
print("4.3")
print(rngArr2, "\n")

rngArr3 = np.random.randint(1,18,(4,2,5))
print("4.4")
print(rngArr3, "\n")

4.1
np.random.seed(888) 

4.2
[-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08510762

In [305]:
# Exercise 5: Split, concatenate, reshape arrays

ex5ArrayLow = np.arange(1, 51)
print(ex5ArrayLow, "\n")
ex5ArrayHigh = np.arange(51, 101)
print(ex5ArrayHigh, "\n")
exConcatenate = np.concatenate((ex5ArrayLow, ex5ArrayHigh))
print(exConcatenate, "\n")
exReshape = np.reshape(exConcatenate, (10,10))
print(exReshape, "\n")


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 

[ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100] 

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53 

In [306]:
# Exercise 6: Broadcasting and Slicing

# 6.1
ex6Array2d = np.ones((9, 9), dtype=np.int8)
print(ex6Array2d, "\n")
# 6.2
ex6Array2d[1:-1, 1:-1] = 0
ex6Array2d[2, 2:7] = 1
ex6Array2d[3:6, 4] = 1
ex6Array2d[4, 2:8:2] = 1
ex6Array2d[6, 2:7] = 1
print(ex6Array2d, "\n")
# 6.3
array_1 = np.array([1,2,3,4,5], dtype=np.int8)
array_2 = np.array([1,2,3], dtype=np.int8)
np.reshape(array_1, (5, 1)) * array_2
print(np.reshape(array_1, (5, 1)) * array_2)


[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]] 

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]] 

[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [307]:
# Exercise 7: NaN

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))
grades[[1,2,5,7], [0,0,0,0]] = np.nan
# print(grades)

gradesWhere = np.where(np.isnan(grades[:, 0]), grades[:, 1], grades[:, 0])
# print(gradesWhere)
gradesInsert = np.insert(arr = grades, values = gradesWhere, axis = 1, obj = 2)
print(gradesInsert)

[[7.00000000 1.00000000 7.00000000]
 [       nan 2.00000000 2.00000000]
 [       nan 8.00000000 8.00000000]
 [9.00000000 3.00000000 9.00000000]
 [8.00000000 9.00000000 8.00000000]
 [       nan 2.00000000 2.00000000]
 [8.00000000 2.00000000 8.00000000]
 [       nan 6.00000000 6.00000000]
 [9.00000000 2.00000000 9.00000000]
 [8.00000000 5.00000000 8.00000000]]


In [308]:
# Exercise 8: Wine

# Load the data using genfromtxt and optimize types
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
optimised_data = np.genfromtxt(url, delimiter=';', skip_header=1, dtype=np.float32)

# Check memory usage
print("8.1")
print(f"Memory Usage: {optimised_data.nbytes} bytes")
# Verify if the dataset size criterion is met
if optimised_data.nbytes <= 76800:
    print("Data optimized successfully.", "\n")
else:
    print("Optimization criteria not met.", "\n")


# Print 2nd, 7th, and 12th rows
print("8.2")
selected_rows = optimised_data[[1, 6, 11]]
print("Selected Rows:")
# Numpy/Python is stonking awful at not adding extra deciam points!
for row in selected_rows:
    print(" ".join(f"{value:.4f}" if isinstance(value, float) else str(value) for value in row))
print()

# Check if any wine has alcohol percentage greater than 20%
print("8.3")
has_high_alcohol = np.any(optimised_data[:, 10] > 20)
print(f"Any wine with alcohol > 20%: {has_high_alcohol}", "\n")

# Compute average % of alcohol, dropping NaN values
print("8.4")
average_alcohol = np.nanmean(optimised_data[:, 10])
print(f"Average % of alcohol: {average_alcohol}", "\n")

# Compute statistics for pH
print("8.5")
ph_stats = {
    '25th Percentile': np.percentile(optimised_data[:, 8], 25),
    '50th Percentile (Median)': np.median(optimised_data[:, 8]),
    '75th Percentile': np.percentile(optimised_data[:, 8], 75),
    'Mean': np.mean(optimised_data[:, 8]),
    'Minimum': np.min(optimised_data[:, 8]),
    'Maximum': np.max(optimised_data[:, 8])
}
for key, value in ph_stats.items():
    print(f"{key}: {value:.2f}")
print("\n")

# Compute average quality of wines with the 20% least sulphates
print("8.6")
percentile_20 = np.percentile(optimised_data[:, 9], 20)
average_quality_20 = optimised_data[optimised_data[:, 9] < percentile_20, 11].mean()
print(f"Average quality of wines with 20% least sulphates: {average_quality_20}", "\n")

# Identify best and worst quality wines
print("8.7")
best_quality = np.argmax(optimised_data[:, 11])
worst_quality = np.argmin(optimised_data[:, 11])

best_quality_indices = np.where(optimised_data[:, 11] == np.max(optimised_data[:, 11]))[0]
worst_quality_indices = np.where(optimised_data[:, 11] == np.min(optimised_data[:, 11]))[0]

best_quality_rows = optimised_data[best_quality_indices]
worst_quality_rows = optimised_data[worst_quality_indices]

# Calculate the mean of each column for these rows
best_mean_values = np.mean(best_quality_rows, axis=0)
worst_mean_values = np.mean(worst_quality_rows, axis=0)

np.set_printoptions(precision=8, suppress=False)
print("best wines mean values")
print(best_mean_values)
print("worst wines mean values")
print(worst_mean_values)

print("\n")

8.1
Memory Usage: 76752 bytes
Data optimized successfully. 

8.2
Selected Rows:
7.8 0.88 0.0 2.6 0.098 25.0 67.0 0.9968 3.2 0.68 9.8 5.0
7.9 0.6 0.06 1.6 0.069 15.0 59.0 0.9964 3.3 0.46 9.4 5.0
7.5 0.5 0.36 6.1 0.071 17.0 102.0 0.9978 3.35 0.8 10.5 5.0

8.3
Any wine with alcohol > 20%: False 

8.4
Average % of alcohol: 10.42298412322998 

8.5
25th Percentile: 3.21
50th Percentile (Median): 3.31
75th Percentile: 3.40
Mean: 3.31
Minimum: 2.74
Maximum: 4.01


8.6
Average quality of wines with 20% least sulphates: 5.185430526733398 

8.7
best wines mean values
[ 8.56666565  0.42333329  0.39111114  2.57777762  0.06844445 13.27777767
 33.44444275  0.99521226  3.26722217  0.76777774 12.09444427  8.00000000]
worst wines mean values
[ 8.35999870  0.88450003  0.17099999  2.63500023  0.12249999 11.00000000
 24.89999962  0.99746400  3.39800000  0.57000005  9.95499992  3.00000000]




In [310]:
# Exercise 9: Football tournament

from itertools import permutations

# Load the model forecasts from the file
model_forecasts = np.genfromtxt('model_forecasts.txt', delimiter=',')
# Generate all possible permutations of team indices

teams = np.arange(10)
all_pairings = np.array(list(permutations(teams)))

# Split the permutation into two groups
half_size = len(teams) // 2
pairings = all_pairings[:, :half_size], all_pairings[:, half_size:]

# Compute sum of squared differences (SSD) for all pairings
ssd = np.sum((model_forecasts[pairings[0], pairings[1]])**2, axis=1)

# Find the pairing with the smallest SSD
best_pairing_idx = np.argmin(ssd)
best_pairing_teams = all_pairings[best_pairing_idx]

# Split the best pairing into two rows
formatted_pairing = np.array([
    best_pairing_teams[:half_size],
    best_pairing_teams[half_size:]
])

print("Exercise 9")
print("Best Match Pairings (Team1 vs Team2):")
print(formatted_pairing)


Best Match Pairings (Team1 vs Team2):
[[0 1 2 3 5]
 [8 7 9 4 6]]
